name: monitoreo-fraude

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: monitoreo-fraude-api
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dashboard
    container_name: monitoreo-fraude-dashboard
    depends_on:
      - api
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://api:8000
      PYTHONUNBUFFERED: "1"
